<a href="https://colab.research.google.com/github/JamorMoussa/Deep-Learning/blob/main/DL-from-scratch/SNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [155]:
import torch 
import torch.nn as nn
import numpy as np 
import torch.nn.functional as F

In [216]:
def f(x):
  return np.sin(x)

In [198]:
class SNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.L1 = nn.Linear(in_features = 2, out_features= 3, bias=True)
        self.L2 = nn.Linear(in_features = 3, out_features= 1, bias=True)
    def forward(self,x):
        self.z1 = self.L1(x)
        self.a1 = F.relu(self.z1)
        self.z2 = self.L2(self.a1)
        return self.z2.squeeze()

In [217]:
[f(x) for x in x_train]

[tensor([0.4184, 0.0114]),
 tensor([-0.9901, -0.4130]),
 tensor([ 0.2858, -0.0442]),
 tensor([ 0.7969, -0.8331]),
 tensor([-0.8884,  0.8627]),
 tensor([ 0.9977, -0.5210]),
 tensor([-0.8251, -0.4032]),
 tensor([0.9563, 0.9746]),
 tensor([ 0.8481, -0.3508]),
 tensor([ 0.7954, -0.0130]),
 tensor([0.8853, 0.7236]),
 tensor([-0.6576,  0.0010]),
 tensor([-0.9171, -0.9436]),
 tensor([-0.8505, -0.9123]),
 tensor([-0.5278,  0.1613]),
 tensor([-0.6599, -0.2196]),
 tensor([-0.4021, -0.0374]),
 tensor([-0.9525, -0.9868]),
 tensor([-0.8592,  0.9352]),
 tensor([ 1.0000, -0.8486]),
 tensor([0.2513, 0.7446]),
 tensor([-0.3746,  0.9675]),
 tensor([-0.9863,  0.5958]),
 tensor([ 0.0510, -0.3470]),
 tensor([0.0701, 0.4409]),
 tensor([ 0.9467, -0.0429]),
 tensor([-0.1735,  0.0046]),
 tensor([0.9151, 0.4037]),
 tensor([0.9856, 0.9761]),
 tensor([-0.8714,  0.8050]),
 tensor([0.7514, 0.5676]),
 tensor([-0.7704, -0.3685]),
 tensor([-0.0140, -0.4258]),
 tensor([ 0.4986, -0.6366]),
 tensor([ 0.5742, -0.4633]),
 

In [214]:
x_train = torch.tensor(20 * torch.rand(100,2) - 10 ).float()
y_train = torch.tensor().float()

<ipython-input-214-566113359c51>:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  x_train = torch.tensor(20 * torch.rand(100,2) - 10 ).float()


ValueError: ignored

In [176]:
y_train[:3]

tensor([ 0.5553, -0.3879,  1.0888])

In [200]:
model = SNN() 
L = nn.MSELoss()
opt = torch.optim.SGD(model.parameters(),lr=0.0001)

In [201]:
for _ in range(1000):
    for X,y in zip(x_train , y_train):
      opt.zero_grad()
      loss_value = L(model(X), y)
      loss_value.backward()
      opt.step()

In [205]:
x_test = torch.tensor([[1,2],
                       [2,-3],
                       [-1,2]]).float()
y_test = torch.tensor([3,-1,1])

In [207]:
(1 - torch.linalg.norm(model(x_test) - y_test))*100

tensor(99.3679, grad_fn=<MulBackward0>)